<?php
namespace Rigo\Types;
    
use WPAS\Types\BasePostType;

class Sample extends BasePostType{
    
    function initialize(){
        add_action('acf/init', array($this, 'add_sample_fields'));
    }

    function add_sample_fields() {
        acf_add_local_field_group(array(
        	'key' => 'group_5b70c8852603b',
        	'title' => 'Sample Field Group',
        	'fields' => array(
        		array(
        			'key' => 'field_5b70c89582627',
        			'label' => 'Text',
        			'name' => 'text',
        			'type' => 'text',
        			'instructions' => '',
        			'required' => 0,
        			'conditional_logic' => 0,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'default_value' => '',
        			'placeholder' => '',
        			'prepend' => '',
        			'append' => '',
        			'maxlength' => '',
        		),
        		array(
        			'key' => 'field_5b70c8b782628',
        			'label' => 'Text Area',
        			'name' => 'text_area',
        			'type' => 'textarea',
        			'instructions' => '',
        			'required' => 0,
        			'conditional_logic' => 0,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'default_value' => '',
        			'placeholder' => '',
        			'maxlength' => '',
        			'rows' => '',
        			'new_lines' => '',
        		),
        		array(
        			'key' => 'field_5b70c8c582629',
        			'label' => 'Number',
        			'name' => 'number',
        			'type' => 'number',
        			'instructions' => '',
        			'required' => 0,
        			'conditional_logic' => 0,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'default_value' => '',
        			'placeholder' => '',
        			'prepend' => '',
        			'append' => '',
        			'min' => '',
        			'max' => '',
        			'step' => '',
        		),
        		array(
        			'key' => 'field_5b70c8db8262a',
        			'label' => 'Range',
        			'name' => 'range',
        			'type' => 'range',
        			'instructions' => '',
        			'required' => 0,
        			'conditional_logic' => 0,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'default_value' => '',
        			'min' => '',
        			'max' => '',
        			'step' => '',
        			'prepend' => '',
        			'append' => '',
        		),
        		array(
        			'key' => 'field_5b70c8f48262b',
        			'label' => 'Image',
        			'name' => 'image',
        			'type' => 'image',
        			'instructions' => '',
        			'required' => 0,
        			'conditional_logic' => 0,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'return_format' => 'array',
        			'preview_size' => 'thumbnail',
        			'library' => 'all',
        			'min_width' => '',
        			'min_height' => '',
        			'min_size' => '',
        			'max_width' => '',
        			'max_height' => '',
        			'max_size' => '',
        			'mime_types' => '',
        		),
        		array(
        			'key' => 'field_5b70c9078262c',
        			'label' => 'File',
        			'name' => 'file',
        			'type' => 'file',
        			'instructions' => '',
        			'required' => 0,
        			'conditional_logic' => 0,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'return_format' => 'array',
        			'library' => 'all',
        			'min_size' => '',
        			'max_size' => '',
        			'mime_types' => '',
        		),
        		array(
        			'key' => 'field_5b70c9138262d',
        			'label' => 'Select',
        			'name' => 'select',
        			'type' => 'select',
        			'instructions' => '',
        			'required' => 0,
        			'conditional_logic' => 0,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'choices' => array(
        				'Select 1' => 'Select 1',
        				'Select 2' => 'Select 2',
        				'Select 3' => 'Select 3',
        			),
        			'default_value' => array(
        			),
        			'allow_null' => 0,
        			'multiple' => 0,
        			'ui' => 0,
        			'return_format' => 'value',
        			'ajax' => 0,
        			'placeholder' => '',
        		),
        		array(
        			'key' => 'field_5b70c9418262e',
        			'label' => 'Checkbox',
        			'name' => 'checkbox',
        			'type' => 'checkbox',
        			'instructions' => '',
        			'required' => 0,
        			'conditional_logic' => 0,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'choices' => array(
        				'fracture' => 'Fracture',
        				'luxation' => 'Luxation',
        				'sprain' => 'Sprain',
        			),
        			'allow_custom' => 0,
        			'default_value' => array(
        			),
        			'layout' => 'vertical',
        			'toggle' => 0,
        			'return_format' => 'value',
        			'save_custom' => 0,
        		),
        		array(
        			'key' => 'field_5b70c9898262f',
        			'label' => 'Radio',
        			'name' => 'radio',
        			'type' => 'radio',
        			'instructions' => '',
        			'required' => 0,
        			'conditional_logic' => 0,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'choices' => array(
        				'Radio 1' => 'Radio 1',
        				'Radio 2' => 'Radio 2',
        				'Radio 3' => 'Radio 3',
        			),
        			'allow_null' => 0,
        			'other_choice' => 0,
        			'default_value' => '',
        			'layout' => 'vertical',
        			'return_format' => 'value',
        			'save_other_choice' => 0,
        		),
        		array(
        			'key' => 'field_5b70c9b782630',
        			'label' => 'Button',
        			'name' => 'button',
        			'type' => 'button_group',
        			'instructions' => '',
        			'required' => 0,
        			'conditional_logic' => 0,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'choices' => array(
        				'Button 1' => 'Button 1',
        				'Button 2' => 'Button 2',
        				'Button 3' => 'Button 3',
        			),
        			'allow_null' => 0,
        			'default_value' => '',
        			'layout' => 'horizontal',
        			'return_format' => 'value',
        		),
        		array(
        			'key' => 'field_5b70ca4382632',
        			'label' => 'Date',
        			'name' => 'date',
        			'type' => 'date_picker',
        			'instructions' => '',
        			'required' => 0,
        			'conditional_logic' => 0,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'display_format' => 'F j, Y',
        			'return_format' => 'Ymd',
        			'first_day' => 0,
        		),
        		array(
        			'key' => 'field_5b70cab282633',
        			'label' => 'Time',
        			'name' => 'time',
        			'type' => 'time_picker',
        			'instructions' => '',
        			'required' => 0,
        			'conditional_logic' => 0,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'display_format' => 'g:i a',
        			'return_format' => 'H:i:s',
        		),
        		array(
        			'key' => 'field_5b737d0d192aa',
        			'label' => 'Monday',
        			'name' => 'monday',
        			'type' => 'relationship',
        			'instructions' => '',
        			'required' => 0,
        			'conditional_logic' => 0,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'post_type' => array(
        				0 => 'post',
        			),
        			'taxonomy' => array(
        			),
        			'filters' => array(
        				0 => 'taxonomy',
        			),
        			'elements' => '',
        			'min' => '',
        			'max' => '',
        			'return_format' => 'object',
        		),
        		array(
        			'key' => 'field_5b737e430e46a',
        			'label' => 'Tuesday',
        			'name' => 'tuesday',
        			'type' => 'relationship',
        			'instructions' => '',
        			'required' => 0,
        			'conditional_logic' => 0,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'post_type' => array(
        				0 => 'training',
        			),
        			'taxonomy' => array(
        			),
        			'filters' => '',
        			'elements' => '',
        			'min' => '',
        			'max' => '',
        			'return_format' => 'object',
        		),
        		array(
        			'key' => 'field_5b737e580e46b',
        			'label' => 'Wednesday',
        			'name' => 'wednesday',
        			'type' => 'relationship',
        			'instructions' => '',
        			'required' => 0,
        			'conditional_logic' => 0,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'post_type' => array(
        				0 => 'training',
        			),
        			'taxonomy' => array(
        			),
        			'filters' => '',
        			'elements' => '',
        			'min' => '',
        			'max' => '',
        			'return_format' => 'object',
        		),
        		array(
        			'key' => 'field_5b737e6a0e46c',
        			'label' => 'Thursday',
        			'name' => 'thursday',
        			'type' => 'relationship',
        			'instructions' => '',
        			'required' => 0,
        			'conditional_logic' => 0,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'post_type' => array(
        				0 => 'training',
        			),
        			'taxonomy' => array(
        			),
        			'filters' => '',
        			'elements' => '',
        			'min' => '',
        			'max' => '',
        			'return_format' => 'object',
        		),
        		array(
        			'key' => 'field_5b737e7c0e46d',
        			'label' => 'Friday',
        			'name' => 'friday',
        			'type' => 'relationship',
        			'instructions' => '',
        			'required' => 0,
        			'conditional_logic' => 0,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'post_type' => array(
        				0 => 'training',
        			),
        			'taxonomy' => array(
        			),
        			'filters' => '',
        			'elements' => '',
        			'min' => '',
        			'max' => '',
        			'return_format' => 'object',
        		),
        	),
        	'location' => array(
        		array(
        			array(
        				'param' => 'post_type',
        				'operator' => '==',
        				'value' => 'sample',
        			),
        		),
        	),
        	'menu_order' => 0,
        	'position' => 'normal',
        	'style' => 'default',
        	'label_placement' => 'top',
        	'instruction_placement' => 'label',
        	'hide_on_screen' => '',
        	'active' => 1,
        	'description' => '',
        ));
    }
}
?>